### ISSUE TITLE
请问实现了群聊系统的 ack 机制吗

### ISSUE THREAD

**Issue by JeffreyBool** [YK-peng/bubble#1]
群聊消息的可靠性得到了保证吗？包含消息重推

**Comment by YK-peng** [comment]
> 群聊消息的可靠性得到了保证吗？包含消息重推

代码还没全部完成。 思路上：消息不需要服务端不停的重复推送。 数据更新模式：通过版本号，增量更新。不需要让客户端来ACK，让服务器去等待客户端，不太合理。   客户端每次点进APP的时候会主动来同步消息下来。 有新消息A来，服务端推送A给客户端，如果这次丢了，下次推B消息的时候，客户端能根据版本好对比出存在丢失消息，会再去服务端同步一次(beforeA~B，这个版本号区间，去服务端查询)

**Comment by YK-peng** [comment]
> > 群聊消息的可靠性得到了保证吗？包含消息重推
> 
> 代码还没全部完成。 思路上：消息不需要服务端不停的重复推送。 数据更新模式：通过版本号，增量更新。不需要让客户端来ACK，让服务器去等待客户端，不太合理。 客户端每次点进APP的时候会主动来同步消息下来。 有新消息A来，服务端推送A给客户端，如果这次丢了，下次推B消息的时候，客户端能根据版本好对比出存在丢失消息，会再去服务端同步一次(beforeA~B，这个版本号区间，去服务端查询)

如果老是丢消息，那么应该是代码逻辑问题，或者网络不稳定。 则应该去除了代码或网络问题

**Comment by JeffreyBool** [comment]
只是想做个这种保证

**Comment by JeffreyBool** [comment]
目前已经基于内存实现了。消息重递队列
